### ISSUE TITLE
human readable output

### ISSUE THREAD

**Issue by rainerrose** [isotopp/tarstats#3]
It would be wonderful if there would be an human readable option (`-H` resp. `--human-readable` ) , something like

~~~
type: archive
name: foo.txz
size: 91m
filesize: 19m
files: 4.568
~~~

**Comment by isotopp** [comment]
Added in 288de2c3a26ad46e8caebae2824b760460237f6a, please test.

**Comment by rainerrose** [comment]
Works as desired. Thank you.
